### PR TITLE
pt_br.lang

### PR DESCRIPTION
**Pull request by AndreiTS**

### CODE REVIEW

**Comment by TheLMiffy1111** [comment]
Please also localize the ore names in zh_CN.lang

**Comment by TheLMiffy1111** [comment]
Please?

**Comment by AndreiTS** [comment]
Sry, give me a couple of days.

**Comment by TheLMiffy1111** [comment]
You do not have to do all the ore names, just the real-life ones and other ones with official translations.

**Comment by TheLMiffy1111** [comment]
Thanks!

**Pull request merged**
