### PR TITLE
Create tr_TR.lang

### PR DESCRIPTION
**Pull request by Emirhangg**
Made by: Emirhangg
Turkish Translation.
If problematic, you can download this:
[tr_TR.zip](https://github.com/TheLMiffy1111/JAOPCA/files/2103066/tr_TR.zip)

### CODE REVIEW

**Comment by TheLMiffy1111** [comment]
please translate material names

**Comment by Emirhangg** [comment]
I can't translate now.

**Comment by TheLMiffy1111** [comment]
doesn't have to be now

**Comment by Emirhangg** [comment]
Can't you accept this?

**Pull request merged**
